version: '3.4'

services:
  console:
    build:
      context: .
      target: dev
    command: bash
    volumes:
      - .:/asciibook
  sut:
    build:
      context: .
      target: dev
      cache_from:
        - asciibook_sut
    command: bundle exec rake test
    volumes:
      - .:/asciibook
