= Asciibook
:toc:

Asciibook is an Ebook generator for converting AsciiDoc to HTML, PDF and EPUB.

== Installation

Asciibook uses docker as distribution tool. Docker helps deal with dependencies, keeps the local environment clean, and works well with CI / CD tools.

You can download and install docker in https://www.docker.com/products/docker-desktop .

After installed docker, Pull the docker image:

[source, consle]
----
$ docker pull asciibook/asciibook
----

== Usage

First, enter container enviroment in your AsciiDoc file diretory:

[source, console]
----
$ docker run -it -v $(pwd):/asciibook asciibook/asciibook bash
/asciibook #
----

Following command is executed inside the container environment.

For a existing AsciiDoc file, run this command to build all formats:

[source, console]
----
/asciibook # ascibook build mybook.adoc
----

Generated results will be placed in the `build` folder.

Or generate partial formats:

[source, console]
----
/asciibook # asciibook build mybook.adoc --format html,pdf,epub
----

If you don't want to type the parameters repeatedly, you can create a configuration file for the document:

[source, console]
----
/asciibook # asciibook init mybook.adoc
----

It will create a config file named `asciibook.yml` in the same directory, edit config for your need, then use this command to build next time:

[source, console]
----
/asciibook # asciibook build
----

== Development

Clone this repo:

[source, console]
----
$ git clone https://github.com/asciibook/asciibook.git
$ cd asciibook
----

Star dev environment with docker:

[source, console]
----
$ docker-compose run console
----

Run test:

[source, console]
----
/asciibook # rake test
----

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/asciibook/asciibook.

== License

The gem is available as open source under the terms of the [MIT License](http://opensource.org/licenses/MIT).
