name: CI/CD

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker-compose build
          docker-compose run sut

  push_to_rubygems:
    needs: testing
    if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem build asciibook.gemspec
          gem push asciibook-*.gem
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}

  push_to_docker:
    needs: testing
    if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v\(.*\)/\1/')
          docker build . --target release --tag asciibook/asciibook:$VERSION --tag asciibook/asciibook:latest
          docker build . --target cjk --build-arg locale=zh_CN.UTF-8 --tag asciibook/asciibook:$VERSION-cjk-sc
          docker build . --target cjk --build-arg locale=zh_TW.UTF-8 --tag asciibook/asciibook:$VERSION-cjk-tc
          docker build . --target cjk --build-arg locale=ja_JP.UTF-8 --tag asciibook/asciibook:$VERSION-cjk-jp
          docker build . --target cjk --build-arg locale=ko_KR.UTF-8 --tag asciibook/asciibook:$VERSION-cjk-kr
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
          docker push asciibook/asciibook:$VERSION
          docker push asciibook/asciibook:latest
          docker push asciibook/asciibook:$VERSION-cjk-sc
          docker push asciibook/asciibook:$VERSION-cjk-tc
          docker push asciibook/asciibook:$VERSION-cjk-jp
          docker push asciibook/asciibook:$VERSION-cjk-kr
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
